package beyond.es.marvelpedia.modelo;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import beyond.es.marvelpedia.modelo.Personaje;
import beyond.es.marvelpedia.modelo.Comic;

import beyond.es.marvelpedia.modelo.PersonajeDao;
import beyond.es.marvelpedia.modelo.ComicDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig personajeDaoConfig;
    private final DaoConfig comicDaoConfig;

    private final PersonajeDao personajeDao;
    private final ComicDao comicDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        personajeDaoConfig = daoConfigMap.get(PersonajeDao.class).clone();
        personajeDaoConfig.initIdentityScope(type);

        comicDaoConfig = daoConfigMap.get(ComicDao.class).clone();
        comicDaoConfig.initIdentityScope(type);

        personajeDao = new PersonajeDao(personajeDaoConfig, this);
        comicDao = new ComicDao(comicDaoConfig, this);

        registerDao(Personaje.class, personajeDao);
        registerDao(Comic.class, comicDao);
    }
    
    public void clear() {
        personajeDaoConfig.getIdentityScope().clear();
        comicDaoConfig.getIdentityScope().clear();
    }

    public PersonajeDao getPersonajeDao() {
        return personajeDao;
    }

    public ComicDao getComicDao() {
        return comicDao;
    }

}
